// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yslifncdfenfrvsqwnmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzbGlmbmNkZmVuZnJ2c3F3bm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Mjg3MDMsImV4cCI6MjA2ODAwNDcwM30.VYMbgTMtthyPtnpuPZA4Bb3uJ3knQLihc4G4ViVcS4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});